<div class="switchSite">
	<p><a href="<?php echo($_SERVER['PHP_SELF'])?>?mobile=no" target="_self">View Full Site</a></p>
</div>
<div class="footer">
	<p>&copy; 2011 - <?php echo date("Y"); ?> LoveToRant.com | <a href="privacy.php" target="_self">Privacy Policy</a></p>
	<p>Site designed and created by Liam Edward Creative</p>
	<p><a href="http://www.liamedward.com">www.LiamEdward.com</a></p>
	
</div>