<div id="topAd" class="topAd">
	<!--<img src="images/320x50PicAd_FPO.png" />-->
	<script type="text/javascript"><!--
  // XHTML should not attempt to parse these strings, declare them CDATA.
  /* <![CDATA[ */
  window.googleAfmcRequest = {
    client: 'ca-mb-pub-0213160955630502',
    format: '320x50_mb',
    output: 'html',
    slotname: '4328417633',
  };
  /* ]]> */
//-->
</script>
<script type="text/javascript"    src="http://pagead2.googlesyndication.com/pagead/show_afmc_ads.js"></script>

</div>